name: shopping_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Ensure you're using a compatible Dart SDK

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  lottie: ^3.1.3
  google_fonts: ^6.2.1  # Use an earlier stable version that doesn't have the issue
  url_launcher: ^6.0.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/loading.json
